### ISSUE TITLE
Heartbeats don't get sent by fixtest client

### ISSUE THREAD

**Issue by speedyyellow** [kennt/fixtest#2]
I'm trying to connect a fixtest client to a server and get the heartbeat working between the two.  The fixtest client never sends a heartbeat message though as it waits too long and the server sends a TestRequest instead.  The client responds to the test request correctly which resets the send time and starts the same loop again.

**Comment by kennt** [comment]
Picked up the changes, Fix is in 0.1.3 on pypi
